// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQ8HcoYXkoqGQTLwsyr0xvZAOBTQGxe0',
    appId: '1:77519242704:web:5d9a9394c0d212be9de5d5',
    messagingSenderId: '77519242704',
    projectId: 'milliyapp-2db0f',
    authDomain: 'milliyapp-2db0f.firebaseapp.com',
    storageBucket: 'milliyapp-2db0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZMnDT1ye7Y2Ybk4IMdF2AHD2fRYq6pZI',
    appId: '1:77519242704:android:b713c055378140989de5d5',
    messagingSenderId: '77519242704',
    projectId: 'milliyapp-2db0f',
    storageBucket: 'milliyapp-2db0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQdYvGx9ihPQoPYUL1S0_S23qDL2ZLoxY',
    appId: '1:77519242704:ios:2e7c4a25cdcc37cb9de5d5',
    messagingSenderId: '77519242704',
    projectId: 'milliyapp-2db0f',
    storageBucket: 'milliyapp-2db0f.firebasestorage.app',
    androidClientId: '77519242704-pjscus0dn3cb3j8jvopo98t6c8bddcqf.apps.googleusercontent.com',
    iosClientId: '77519242704-754dbi986ufl1r8j5qe3mtriivbpgdij.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQdYvGx9ihPQoPYUL1S0_S23qDL2ZLoxY',
    appId: '1:77519242704:ios:2e7c4a25cdcc37cb9de5d5',
    messagingSenderId: '77519242704',
    projectId: 'milliyapp-2db0f',
    storageBucket: 'milliyapp-2db0f.firebasestorage.app',
    androidClientId: '77519242704-pjscus0dn3cb3j8jvopo98t6c8bddcqf.apps.googleusercontent.com',
    iosClientId: '77519242704-754dbi986ufl1r8j5qe3mtriivbpgdij.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByQ8HcoYXkoqGQTLwsyr0xvZAOBTQGxe0',
    appId: '1:77519242704:web:7b5e8961753656149de5d5',
    messagingSenderId: '77519242704',
    projectId: 'milliyapp-2db0f',
    authDomain: 'milliyapp-2db0f.firebaseapp.com',
    storageBucket: 'milliyapp-2db0f.firebasestorage.app',
  );

}